Multibyte write and copy
fvdhoef/vera-module pull request #32
Opened 2023-01-25 19:41 UTC by visual-trials

This change allows for multibyte writing and copying of VRAM data. Its main purpose is to increase performance.

Colums: address % 4
Rows: 2-bit value representing a pattern (but dependent on addrss, so we can create all possible patterns)
	
```
_   0    1    2    3
00 0001 0010 0100 1000
01 0011 0110 1100 1001
10 0101 1010 0111 1110
11 1111 1111 1101 1011

```

Use cases:

- Clearing a bitmap screen 4 times as fast
- Drawing (large) polygons much faster
- Drawing multiple pixels column at the same time (like deferred rendering worked for VGA, for example in DOOM and Wolfenstein 3D).
- Copying tiledata 4 times as fast (for tile animations)
- Copying bitmap data 4 times as fast

2023-01-25 21:25 UTC, jburks commented
Need some more detail regarding the write patterns: while some of them are obvious, e.g. `1111` for contiguous fill and `1010` and `0101` for tile updates, some patterns such as `1101` are not. Would it be better to reserve some of the patterns for future use?

2023-01-25 21:26 UTC, jburks commented
What is the resource impact (e.g. additional LUT4s used) for adding this capability?

2023-01-25 21:35 UTC, jburks requested changes
Good design, just some aesthetic cleanup needed that I can see.

2023-01-25 21:35 UTC, jburks commented on fpga/source/top.v
> +	reg [16:0] ib_addr_tmp;
Nit: use four spaces instead of tabs (multiple instances of this in this file, all of them should be fixed).

2023-01-25 21:35 UTC, jburks commented on fpga/source/top.v
> +    reg [31:0] ib_cache32_r, ib_cache32_next;
Nit: line up `ib_cache32_next` with other _next regs above it.

2023-01-25 21:35 UTC, jburks commented on fpga/source/vram_if.v
> +    always @* case (if0_wrpattern[1:0])
In cases like this, I prefer to avoid nested case statements. I would use `case ({if0_wrpattern[1:0], if0_addr[1:0]}`. Minor point and could be left as is.

2023-01-25 21:41 UTC, jburks commented
It feels like there needs to be a formal review process for features like this to avoid unnecessary feature creep and ensure we aren't getting away from the original "retro" vision by adding too many advanced capabilities. This particular addition doesn't bother me since it feels like what advanced 8-bit hardware might have had as a steppingstone between the CPU doing everything and a full-blown blitter like the Amiga had. That said, we need people in the room who aren't microarchitecture experts and therefore are not likely to review this as part of the decision-making process.

2023-01-26 16:43 UTC, visual-trials commented on fpga/source/vram_if.v
> +    always @* case (if0_wrpattern[1:0])
Yes, I understand. But in this case I wanted to create the same kind of structure as the table in the comments above. If you put all bits together it might not be clear where a row in the table starts or ends. This way it does.

2023-01-26 16:54 UTC, visual-trials commented on fpga/source/top.v
> +    reg [31:0] ib_cache32_r, ib_cache32_next;
Whitespaces added

2023-01-26 16:54 UTC, visual-trials commented on fpga/source/top.v
> +	reg [16:0] ib_addr_tmp;
Tabs replaced by whitespaces.

2023-01-26 22:35 UTC, visual-trials commented
> Need some more detail regarding the write patterns: while some of them are obvious, e.g. `1111` for contiguous fill and `1010` and `0101` for tile updates, some patterns such as `1101` are not. Would it be better to reserve some of the patterns for future use?

I have extended the use cases (see above) explaining/showing 9 multibyte useful patterns. Adding the default 4 single byte patterns to that (and the blit usecase) means there are 14 (out of 16) useful patterns. The two others are not easily used for anything else. So it makes sense just to complete the set of _possible_ byte patterns.

2023-01-28 01:14 UTC, blinkdog commented
In the description of the issue, you've got this written as the 4-bytes-at-once example:
```asm
lda #1          ; Set address to % 4 == 1
sta $9F20
lda #0
sta $9F21

lda #%00110110  ; Set increment to 4 and bits 1 and 2 to 11b
sta $9F22

lda #42
sta DATA0       ; Write color value 4 bytes at a time
sta DATA0
sta DATA0
sta DATA0
sta DATA0
sta DATA0
```
This example uses the `(ADDRESS % 4 == 1)` and `Register Bits 11`,
which according to the table is the `-+++` pattern.

It seems the pattern you'd want to use for this example is `++++`,
which corresponds to `(ADDRESS % 4 == 0)` and `Register Bits 10` from the table.

So is the table wrong, or the example wrong, or have I misunderstood both really badly?

2023-01-28 01:26 UTC, mooinglemur commented
@blinkdog good catch.

The example is wrong.  The four-byte write used to be at wrpattern ($9F22 bits 1 and 2) 11b, address % 0 == 1, but today @visual-trials moved it to wrpattern 10b, address % 0 == 0.  It seems he might have missed updating the example.

2023-01-28 01:41 UTC, mooinglemur commented
I've updated my fork/branch of the emulator to match the current behavior of this PR.  Builds can be found here https://github.com/mooinglemur/x16-emulator/actions/runs/4029536711

2023-01-28 09:06 UTC, visual-trials commented
> In the description of the issue, you've got this written as the 4-bytes-at-once example:
> 
> ```assembly
> lda #1          ; Set address to % 4 == 1
> sta $9F20
> lda #0
> sta $9F21
> 
> lda #%00110110  ; Set increment to 4 and bits 1 and 2 to 11b
> sta $9F22
> 
> lda #42
> sta DATA0       ; Write color value 4 bytes at a time
> sta DATA0
> sta DATA0
> sta DATA0
> sta DATA0
> sta DATA0
> ```
> 
> This example uses the `(ADDRESS % 4 == 1)` and `Register Bits 11`, which according to the table is the `-+++` pattern.
> 
> It seems the pattern you'd want to use for this example is `++++`, which corresponds to `(ADDRESS % 4 == 0)` and `Register Bits 10` from the table.
> 
> So is the table wrong, or the example wrong, or have I misunderstood both really badly?

Thanks! I fixed this in the example code.

2023-01-28 09:33 UTC, visual-trials commented
Here is the reasoning being the choices made in the mapping:

![image](https://user-images.githubusercontent.com/17767704/215258766-a31bf8a2-e5c6-40f3-b92f-8932bed5fcff.png)

This has been discussed in discord, but I though it might be a good idea to post it here as well.

2023-08-08 07:02 UTC, visual-trials commented
There has been a complete rewrite of this, so this is old and can be removed.

2023-08-08 07:02 UTC, closed without merging

2023-08-08 07:02 UTC, visual-trials commented
Closing